---
- hosts: webservers
  become: True
  tasks:
   - name: pulling image
     command: docker pull pratheeknk1205/nodejsapp:0.1
   
   - name: run
     command: docker run -p 5000:3000 pratheeknk1205/nodejsapp:0.1
